export {default as Home} from "./Home/Home"
export {default as About} from "./About/About"
export {default as Projects} from "./Work/Projects"
export {default as Experience} from "./Experience/Experience"
export {default as Skills} from "./Skills/Skills"
export {default as Education} from "./Education/Education"
export {default as Contact} from "./Contact/Contact"
export {default as Footer} from "./Footer/Footer"